name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile, test, and package modules
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Compile, test, and package modules
        run: ./bin/cibuild

      - name: Generate coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./target/site/jacoco/jacoco.xml
          name: codecov
